import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WordChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Este el titulo de cabezera</h1>
      
        <ul>
          <li>
            <Link href="/tienda">Ir a tienda</Link>
          </li>
          <li>
            <Link href="/categoria">Ir a categoria</Link>
          </li>
          <li>
            <Link href="/user">Ir a usuarios</Link>
          </li>
        </ul>

        {children}
      </body>
    </html>
  );
}
